### ISSUE TITLE
LTS model for LPBA40 dataset

### ISSUE THREAD

**Issue by Bala93** [uncbiag/LTS#1]
Could you also add LTS model for other datasets used ?

**Comment by icebergandwind** [comment]
It is pretty much similar to the one provided. The only difference is might be the number of labels for different datasets. Besides, you do not need to be restricted on specific network designs, people use other simple designs can yield similar performance improvement.

**Comment by Bala93** [comment]
Thank your @icebergandwind. The suggestion really helped. Moreover, the cross validation split for smaller valid samples (supplementary material) was very useful.
